version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  mongodb:
    image: mongo
    env_file:
      - .env
    container_name: ${MONGO_DB}
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
