version: '3'

services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - postgres
    env_file:
      - .env
    container_name: ${APP_NAME}
    ports:
      - '${APP_PORT}:${APP_PORT}'
